config/routes.rb
Nagatha::Application.routes.draw do
  resources :todos, :as => :todo_items, :controller => 'todo_items'

  devise_for :users

  get "home/index"

  post "incoming_email/receive"

  root :to => 'home#index'

  resources :todo_items, :except => :show do
    member do
      put 'move_higher'
      put 'move_lower'
      put 'done'
    end
  end

  match '/todos' => 'todo_items#index', :as => 'user_root' # user_root_path - Devise will go here after login

  match 'admin' => 'admin/home#index'

  namespace :admin do
    resource :settings, :only => [:edit, :update]
    resources :users
  end

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :user
  acts_as_list :scope => :user

  validates_presence_of :description
  validates_presence_of :user_id, :message => I18n.t('errors.must_be_supplied')

  state_machine :status, :initial => 'undone' do
    event(:done) { transition 'undone' => 'done' }
  end

  class << self
    def search(search)
      if search
        where('description LIKE ?', "%#{search}%")
      else
        scoped
      end
    end
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_todo_item, :except => [:index, :new, :create]
  helper_method :sort_column, :sort_direction

  def index
    @todo_items = current_user.todo_items.with_status('undone').all
    @machines = TodoItem.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 20, :page => params[:page])
  end

  def new
    @todo = TodoItem.new
  end

  def edit
  end

  def create
    @todo = current_user.todo_items.new(params[:todo_item])

    if @todo.save
      @todo.move_to_top
      redirect_to(todo_items_url, :notice => "Todo item \"#{@todo.description}\" created.")
    else
      flash[:alert] = 'There was a problem creating your To Do item'
      render :action => "new"
    end
  end

  def update
    if @todo.update_attributes(params[:todo_item])
      redirect_to(todo_items_url, :notice => 'Todo item was successfully updated.')
    else
      flash[:alert] = 'There was a problem updating your To Do item'
      render :action => "edit"
    end
  end

  def destroy
    @todo.destroy

    redirect_to(todo_items_url)
  end

  def move_higher
    @todo.move_higher
    redirect_to :action => :index
  end

  def move_lower
    @todo.move_lower
    redirect_to :action => :index
  end

  def done
    @todo.completed_at = Time.now
    @todo.done!
    redirect_to :action => :index
  end

  private

  def load_todo_item
    @todo = current_user.todo_items.find(params[:id])
  end

  def sort_column
    TodoItem.column_names.include?(params[:sort]) ? params[:sort] : "position"
  end

  def sort_direction
    %w{ asc desc }.include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/todo_items/_form.html.haml
= form_for(@todo) do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2
        = pluralize(@todo.errors.count, "error")
        prohibited this todo_item from being saved:

      %ul 
      - @todo.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :description
    %br
    = f.text_field :description
  .actions
    = f.submit

app/views/todo_items/edit.html.haml
%h1 Editing todo_item

= render 'form'

= link_to 'Back', todo_items_path

app/views/todo_items/index.html.haml
%h1 Your To Do List

%table 
  %tr 
    %th Description
    %th Position
    %th
    %th
  - @todo_items.each do |todo_item|
    %tr
      %td= todo_item.description
      %td= todo_item.position
      %td= link_to 'Edit', edit_todo_item_path(todo_item)
      %td= link_to 'Move Up', move_higher_todo_item_path(todo_item), :method => :put unless todo_item.first?
      %td= link_to 'Move Down', move_lower_todo_item_path(todo_item), :method => :put unless todo_item.last?
      %td= link_to 'Destroy', todo_item, :confirm => 'Are you sure?', :method => :delete
      %td= link_to 'Done!', done_todo_item_path(todo_item), :method => :put
%br
= link_to 'New Todo item', new_todo_item_path

app/views/todo_items/new.html.haml
%h1 New todo_item

= render 'form'

= link_to 'Back', todo_items_path