config/routes.rb
Nagatha::Application.routes.draw do
  resources :todos, :as => :todo_items, :controller => 'todo_items'

  devise_for :users

  get "home/index"

  post "incoming_email/receive"

  root :to => 'home#index'

  resources :todo_items, :except => :show do
    member do
      put 'move_higher'
      put 'move_lower'
      put 'done'
    end
  end

  match '/todos' => 'todo_items#index', :as => 'user_root' # user_root_path - Devise will go here after login

  match 'admin' => 'admin/home#index'

  namespace :admin do
    resource :settings, :only => [:edit, :update]
    resources :users
  end

end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < BaseController
    def edit
      @settings = AppConfiguration.instance
    end

    def update
      @settings = AppConfiguration.instance
      if @settings.update_attributes params[:app_configuration]
        flash[:notice] = t('settings_saved')
        redirect_to edit_admin_settings_path
      else
        flash[:alert] = @settings.errors.full_messages
        render :edit
      end
    end
  end
end

app/views/admin/settings/edit.html.haml
%h1= t('navigation.admin.site_settings')
= form_for @settings, :url => admin_settings_path do |f|
  %table.vertical-form
    %tr
      %th
        = t('site_availability.legend')
      %td
        - SiteAvailability.for_select.each do |name, value|
          = f.radio_button :site_availability, value
          = name
          %br
    %tr
      %td
      %td= f.submit t('crud.save')