config/routes.rb
Nagatha::Application.routes.draw do
  resources :todos, :as => :todo_items, :controller => 'todo_items'

  devise_for :users

  get "home/index"

  post "incoming_email/receive"

  root :to => 'home#index'

  resources :todo_items, :except => :show do
    member do
      put 'move_higher'
      put 'move_lower'
      put 'done'
    end
  end

  match '/todos' => 'todo_items#index', :as => 'user_root' # user_root_path - Devise will go here after login

  match 'admin' => 'admin/home#index'

  namespace :admin do
    resource :settings, :only => [:edit, :update]
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :todo_items, :order => "position"
  
  # Include default devise modules. Others available are:
  # :token_authenticatable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def admin?
    role == 'admin' && confirmed_at && !locked_at
  end

  def self.search(search)
    if search
      where('email LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    load_and_authorize_resource
    helper_method :sort_column, :sort_direction

    def index
      @users = User.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
    end

    private

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "email"
    end

    def sort_direction
      %w{ asc desc }.include?(params[:direction]) ? params[:direction] : "asc"
    end
  end
end

app/views/admin/users/_users.html.haml
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]
= will_paginate @users
%table.horizontal-form
  %tr
    %th.email=           sortable :email,              t('activerecord.attributes.user.email')
    %th.role=            sortable :role,               t('activerecord.attributes.user.role')
    %th.sign_in_count=   sortable :sign_in_count,      t('activerecord.attributes.user.sign_in_count')
    %th{ :colspan => 2}= sortable :current_sign_in_at, t('current_sign_in')
    %th{ :colspan => 2}= sortable :last_sign_in_at,    t('last_sign_in')
    %th.created_at=      sortable :created_at,         t('activerecord.attributes.user.created_at')
    %th.confirmed_at=    sortable :confirmed_at,       t('activerecord.attributes.user.confirmed_at')
    %th.locked_at=       sortable :locked_at,          t('activerecord.attributes.user.locked_at')
  %tr
    %th{ :colspan => 3 }
    %th.current_sign_in_at= sortable :current_sign_in_at, t('at')
    %th.current_sign_in_ip= t('from_ip')
    %th.last_sign_in_at=    sortable :last_sign_in_at, t('at')
    %th.last_sign_ip_ip=    t('from_ip')
    %th{ :colspan => 5 }

  - @users.each do |user|
    %tr{ :class => cycle('odd', 'even') }
      %td.email=              user.email
      %td.role=               user.role
      %td.sign_in_count=      user.sign_in_count
      %td.current_sign_in_at= time_ago(user.current_sign_in_at)
      %td.current_sign_in_ip= user.current_sign_in_ip
      %td.last_sign_in_at=    time_ago(user.last_sign_in_at)
      %td.last_sign_in_ip=    user.last_sign_in_ip
      %td.created_at=         time_ago(user.created_at)
      %td.confirmed_at=       time_ago(user.confirmed_at)
      %td.locked_at=          time_ago(user.locked_at)

app/views/admin/users/index.html.haml
%h1= t('users')
= form_tag admin_users_path, :method => 'get', :id => 'users_search' do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag t(:search), :name => nil

  #users
    = render 'users'

app/views/admin/users/index.js.erb
$('#users').html('<%= escape_javascript(render("users")) %>');